# Generated by Django 5.1.6 on 2025-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/defaultpfp.jpg', null=True, upload_to='user_avatar', verbose_name='Аватарка'),
        ),
    ]
